export type ActiveTool =
    'templates'
    | 'image'
    | 'text'
    | 'shapes'
    | 'ai'
    | 'settings'
    | 'draw'
    | 'fill'
    | 'stroke-color'
    | 'stroke-width'
    | 'font'
    | 'opacity'
    | 'remove-bg'
    | 'select'
